albedocompat-1.0 removed due to crash with albedo itself
```
java.lang.NoSuchMethodError: elucent.albedo.lighting.LightManager.addLight(Lelucent/albedo/lighting/Light;)V
    at com.possibletriangle.albedocompat.AlbedoCompat.onProfileStart(AlbedoCompat.java:134)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_9769_AlbedoCompat_onProfileStart_ProfilerStartEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at elucent.albedo.event.ProfilerStartEvent.postNewEvent(ProfilerStartEvent.java:15)
    at net.minecraft.profiler.Profiler.endStartSection(Profiler.java:149)
    at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1324)
    at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1259)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1062)
    at net.minecraft.client.Minecraft.runGameLoop(MinecraftMixin.java:1119)
    at net.minecraft.client.Minecraft.run(MinecraftMixin.java:16614)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
    at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
    at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)